apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-fastapi
  labels:
    app: myapp-fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-fastapi
  template:
    metadata:
      labels:
        app: myapp-fastapi
    spec:
      containers:
        - name: myapp 
          image: fastapi
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8000
