apiVersion: v1
kind: Service
metadata:
  name: myapp-fastapi
spec:
  type: NodePort
  selector:
    app: myapp-fastapi  # Changed from matchLabels to simple selector (both work, but be consistent)
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
